# Generated by Django 4.0.2 on 2022-05-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('stuid', models.IntegerField(primary_key=True, serialize=False)),
                ('stuName', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=10)),
                ('fees', models.IntegerField()),
            ],
        ),
    ]
