# Generated by Django 4.0.3 on 2022-05-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('stuId', models.IntegerField(primary_key=True, serialize=False)),
                ('stuName', models.CharField(max_length=30)),
                ('courseName', models.CharField(max_length=50)),
            ],
        ),
    ]
