# Generated by Django 4.0.2 on 2022-05-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseId', models.IntegerField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=50)),
                ('branchName', models.CharField(max_length=10)),
            ],
        ),
    ]
