# Generated by Django 4.0.2 on 2022-05-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseDate',
            field=models.CharField(default='not available', max_length=20),
        ),
    ]
