# Generated by Django 4.0.2 on 2022-05-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('StuId', models.IntegerField(primary_key=True, serialize=False)),
                ('StuName', models.CharField(max_length=30)),
                ('StuBranch', models.CharField(max_length=20)),
                ('StuFee', models.IntegerField()),
            ],
        ),
    ]
